### PR TITLE
add Charon IPSEC parser, scenario and collection

### PR DESCRIPTION
**Pull request by darkclip**

### CODE REVIEW

**Comment by darkclip** [comment]
@LaurenceJJones I haven't got the opportunity to test that. But from looking at the log format, I would say yes.

**Comment by LaurenceJJones** [comment]
Any chance we can decouple the naming away from OPNSense then and use the application name Charon?

**Comment by darkclip** [comment]
should I just rename the files, and push a new commit?

**Comment by LaurenceJJones** [comment]
> should I just rename the files, and push a new commit?

Rename everything opnsense related to charon and you have to redo the tests files sine they use the parser name

**Comment by darkclip** [comment]
OK, I'll do another push latter.

**Review by LaurenceJJones — APPROVED** [review]
LGTM

**Pull request merged**
