### PR TITLE
Fix Nextcloud-Whitelist: missing expressions for Nextcloud Bookmarks #1089

### PR DESCRIPTION
**Pull request by florianwgnr**
Fix missing expressions for Nextcloud Bookmarks #1089

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Could we have some test log lines so we can add them to the whitelist testing files?

You can redact any PII data just use `<ip>` or `<data>` for placeholders I can `sed` them later

**Comment by florianwgnr** [comment]
Of couse - here is a part of my nginx log when opening Nextcloud Bookmarks: 
```

123.1.234.123 - - [06/Aug/2024:21:01:57 +0200] "GET /apps/bookmarks/bookmark/155/favicon HTTP/2.0" 404 8304 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
123.1.234.123 - - [06/Aug/2024:21:01:57 +0200] "GET /apps/bookmarks/bookmark/460/image HTTP/2.0" 404 8307 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
123.1.234.123 - - [06/Aug/2024:21:01:57 +0200] "GET /apps/bookmarks/bookmark/460/favicon HTTP/2.0" 404 8304 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
123.1.234.123 - - [06/Aug/2024:21:01:57 +0200] "GET /apps/bookmarks/bookmark/343/favicon HTTP/2.0" 404 8303 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
123.1.234.123 - - [06/Aug/2024:21:01:57 +0200] "GET /apps/bookmarks/bookmark/155/image HTTP/2.0" 404 8301 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
123.1.234.123 - - [06/Aug/2024:21:01:57 +0200] "GET /apps/bookmarks/bookmark/343/image HTTP/2.0" 404 8306 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
123.1.234.123 - - [06/Aug/2024:21:01:59 +0200] "GET /apps/bookmarks/folder/3/publictoken HTTP/2.0" 404 39 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"

```

**Comment by LaurenceJJones** [comment]
Fix:  #1089

**Comment by LaurenceJJones** [comment]
Fix: #1089

**Pull request merged**
