### PR TITLE
Update Zoneminder, syslog and pf.

### PR DESCRIPTION
**Pull request by baudneo**
pf and syslog - Added/updated OPNsense style syslogs.
pf: More GROK patterns and parsed data.
opnsense: added pf collection from firewallservices - user needs to add pf filter logs to acquis (I have forked opnsense plugin and working on a PR to make this autonomous).
zoneminder: web_php parser is now datetime agnostic.
Updated tests to include OPNsense logs and new assertions.

### CODE REVIEW

**Comment by baudneo** [comment]
Will fix the other tests today. I am noticing that the crowdsec grok parser seems to act differently than the online grok debuggers.

For pf-logs, it seems ipv4 is not parsing the src_port, dst-port and length via crowdsec but parses fine in online grok debuggers.

**Comment by baudneo** [comment]
There is something VERY strange with how crowdsec parses the GROK patterns.

Example:
```
## message: 59576,22,0,S,17536001,,65535,,mss
pattern_syntax:
  PF_UDP_DATA: '%{INT:src_port},%{INT:dst_port},%{INT:data_length}'
  PF_TCP_DATA: '%{PF_UDP_DATA:TCP_SOURCE_PORTS},%{WORD:tcp_flags}?,%{DATA:tcp_seq}?,%{DATA:tcp_ack}?,%{DATA:tcp_window}?,%{DATA:urg_data}?,%{TCP_OPTS:tcp_options}?'
  PF_PROTOCOL_DATA: '(%{PF_TCP_DATA}|%{PF_UDP_DATA:UDP_SOURCE_PORTS})'
grok:
 pattern: "%{PF_PROTOCOL_DATA}"
 apply_on: message
```
Results:
```
results["s01-parse"]["firewallservices/pf-logs"][15].Evt.Parsed["tcp_seq"] == "17536001"
results["s01-parse"]["firewallservices/pf-logs"][15].Evt.Parsed["tcp_flags"] == "S"
results["s01-parse"]["firewallservices/pf-logs"][15].Evt.Parsed["TCP_SOURCE_PORTS"] == "59576,9090,0"
results["s01-parse"]["firewallservices/pf-logs"][15].Evt.Parsed["tcp_options"] == "mss"
results["s01-parse"]["firewallservices/pf-logs"][15].Evt.Parsed["tcp_window"] == "65535"
```
The `Parsed` dict is missing **src_port**, **dst_port** and **data_length** but `TCP_SOURCE_PORTS` is set meaning that the GROK pattern was successful. So where are those data points?

I have searched and tried many commands at many different log levels to try and see how crowdsec GROK parsing happens but I have not been successful. Is there a way to see whats happening with the GROK? or how the `Parsed` dict keys are being set/popped?

 If I change the GROK pattern to ->
```
GROK:
  PF_UDP_DATA: '%{INT:UDPsrc_port},%{INT:UDPdst_port},%{INT:UDPdata_length}'
  PF_TCP_DATA: '%{INT:TCPsrc_port},%{INT:TCPdst_port},%{INT:TCPdata_length},%{WORD:tcp_flags}?,%{DATA:tcp_seq}?,%{DATA:tcp_ack}?,%{DATA:tcp_window}?,%{DATA:urg_data}?,%{TCP_OPTS:tcp_options}?'
  PF_PROTOCOL_DATA: '(%{PF_TCP_DATA}|%{PF_UDP_DATA:UDP_SOURCE_PORTS})'
```
Then TCPsrc_port, TCPdst_port and TCPdata_length are in the `Parsed` dict. I can than use `statics` to set `evt.Parsed.dst_port`using an expression

Also, just figured out that dateparse enricher is a hard requirement for scenarios to run at all, unless its `evt.StrTime` or `Meta.timestamp` that needs to be set for scenarios to run?

**Comment by LaurenceJJones** [comment]
Hey sorry for being absent and not replying to this.

>Also, just figured out that dateparse enricher is a hard requirement for scenarios to run at all, unless its evt.StrTime or Meta.timestamp that needs to be set for scenarios to run?

Yes evt.StrTime needs to be set. You can see [here](https://hub.crowdsec.net/author/crowdsecurity/configurations/dateparse-enrich) the value passed into the expression.

the GROK pattern is GROK and RE2 so it can have odd behaviours sometimes. I struggle sometimes with optional data I have to wrap them in `()` before other variables can be set.

Also there is a lot of changes in this PR could we ask for you to split them into multiple so if we have an issue with one it doesnt block the other from being merged.

**Comment by baudneo** [comment]
Hi,

No worries I will split this PR up. I should have it done by end of weekend.

Also putting in some PR's for OPNsense plugin and home assistant plugin.

**Comment by LaurenceJJones** [comment]
Converting to draft, please update as per as conversation then we can reopen it

**Pull request closed without merging**
