### PR TITLE
CouchDB Parsers/Scenario

### PR DESCRIPTION
**Pull request by Killian-Aidalinfo**
Hello CrowdSec team! 

Here's a new PR to add parsers/scenarios of bruteforce and Crawl of CouchDB logs. This allows better security on the WAN with the BF, the crawl can be useful if there is no reverse proxy in front.

Thanks a lot !

### CODE REVIEW

**Comment by Killian-Aidalinfo** [comment]
Ok I think it's all good! Please let me know of any improvements I can make :)

**Comment by LaurenceJJones** [comment]
Hey 👋 

Thank you for opening a PR I allocate sometime to review next week!

**Comment by Killian-Aidalinfo** [comment]
Thanks!

**Comment by Killian-Aidalinfo** [comment]
@LaurenceJJones Could you check please for merge ? Thanks!

**Review by LaurenceJJones — APPROVED** [review]
LGTM

**Pull request merged**
