### PR TITLE
Add Authelia parser, scenario and collection

### PR DESCRIPTION
**Pull request by LePresidente**
Add Authelia parser, scenario and collection

Works on both CLF and JSON log format.
Works with a single username or Email Address for the username.
Checks 2FA as well that I was able to test TOTP and DUO

### CODE REVIEW

**Comment by blotus** [comment]
Hello @LePresidente,

Thanks for the PR.

The tests are currently failing due to a case mismatch between `lepresidente` and `LePresidente`, once this is fixed we should be able to merge.

**Review by sabban — APPROVED** [review]
lgtm

**Comment by youngt2** [comment]
@LePresidente I have installed this collection with docker  crowdsec:v1.3.2. However, I noticed that I get a lot of errors from it similar to the below:
```
time="07-03-2022 12:06:27" level=debug msg="eval variables:" cfg=long-resonance file=/etc/crowdsec/scenarios/authelia-bf.yaml name=LePresidente/authelia-bf
time="07-03-2022 12:06:27" level=debug msg="       evt.Meta.log_type = 'ssh_failed-auth'" cfg=long-resonance file=/etc/crowdsec/scenarios/authelia-bf.yaml name=LePresidente/authelia-bf
time="07-03-2022 12:06:27" level=debug msg="Event leaving node : ko (filter mismatch)" cfg=long-resonance file=/etc/crowdsec/scenarios/authelia-bf.yaml name=LePresidente/authelia-bf
time="07-03-2022 12:06:27" level=debug msg="eval(evt.Meta.log_type in ['authelia_failed_clf_auth', 'authelia_failed_json_auth']) = FALSE" cfg=long-resonance file=/etc/crowdsec/scenarios/authelia-bf.yaml name=LePresidente/authelia-bf
```
I also noticed that the parser seems to be pulling from all of my logs rather than just the authelia log. When I inspect the parser I see:

```
Current metrics :

 - (Parser) LePresidente/authelia-logs:
+-------------------------------------------+------+--------+----------+
|                  PARSERS                  | HITS | PARSED | UNPARSED |
+-------------------------------------------+------+--------+----------+
| file:/var/log/authelia/authelia.log       |    5 |      2 |        3 |
| file:/var/log/traefik/access.log          |    6 |      0 |        6 |
| file:/var/log/vaultwarden/vaultwarden.log |    3 |      0 |        3 |
| file:/var/log/auth.log                    |   58 |      0 |       58 |
+-------------------------------------------+------+--------+----------+
```

I don't see this behavior from other parsers, but I'm not sure if I did something wrong with the authelia setup.

**Comment by LePresidente** [comment]
The first log issue is due to a bad debug line in the authelia-bf file that was missed sorry about that.
Fixed in https://github.com/crowdsecurity/hub/pull/411

Regarding your second issue, what does your acquis.yaml file look like since I don't see that issue on my side

**Comment by youngt2** [comment]
No worries! Thought maybe I did something wrong.
My acquis.yaml looks like the below. Nothing unusual in my log files that I saw during initialization. All the lines seems like the standard 'info' lines regarding crowdsec start up.
```
filenames:
 - /var/log/traefik/access.log
labels:
  type: traefik

---
filenames:
  - /var/log/auth.log
labels:
  type: syslog

---
filenames:
 - /var/log/vaultwarden/vaultwarden.log
labels:
  type: Vaultwarden

---
filenames:
 - /var/log/authelia/authelia.log
labels:
  type: authelia
```
Thanks for the fast reply!

**Comment by LePresidente** [comment]
ok both issues are fixed in the pull request above.

**Comment by youngt2** [comment]
Maybe a dumb question, but how do I update? Have to wait for the pull request to be merged first, I believe.
Then I only have to run `cscli parsers upgrade LePresidente/authelia-logs`? Or is it a recreation of the docker service? Or either?

I'm a bit confused by all parsers, bouncers, etc being in the actual crowdsec hub repo.

**Comment by LePresidente** [comment]
as soon as its merged you can do `cscli hub update && cscli hub upgrade`
@blotus can you please look at https://github.com/crowdsecurity/hub/pull/411

**Pull request merged**
