### PR TITLE
add Mikrotik support

### PR DESCRIPTION
**Pull request by a1ad**
Hi,

I created a collection for Mikrotik firewalls:
- parser 
- portscan scenario

You need to setup a rsyslog server and parse the logs on the server. 

edit:
My second commit is my take to add brute force detection, I don't know if this is the "Crowdsec" way to add a second parser. The auth logs and the firewall logs are quite different. So please give it a thorough check.

### CODE REVIEW

**Comment by a1ad** [comment]
Hmm looking at the examples on the Hub I rewrote the parser to combine firewall and auth parsing from this:

```
onsuccess: next_stage
#debug: true
filter: "evt.Parsed.program == 'mikrotik' and evt.Parsed.message contains 'input:'"
name: a1ad/mikrotik-logs
description: "Parse Mikrotik firewall input logs"
grok:
  pattern: "%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME} .* %{DATA:tag} input: in:%{DATA:if_in} out:%{DATA:if_out}, .* src-mac %{MAC:src_mac}, proto %{WORD:proto}.*, %{IP:src_ip}:%>
  apply_on: message
statics:
    - meta: service
      value: tcp_udp
    - meta: log_type
      value: mikrotik_drop
    - target: evt.StrTime
      expression: "evt.Parsed.timestamp"
    - meta: source_ip
      expression: "evt.Parsed.src_ip"

---

onsuccess: next_stage
#debug: true
filter: "evt.Parsed.program == 'mikrotik' and evt.Parsed.message contains 'login'"
name: a1ad/mikrotik-logs
description: "Parse Mikrotik auth logs"
grok:
  #2023-03-19T12:34:09.757188+01:00 10.120.127.1 system,error,critical login failure for user admin from 10.127.0.35 via winbox
  pattern: "%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME} .* login failure for user %{USERNAME:invalid_user} from %{IP:source_ip}"
  apply_on: message
statics:
    - meta: service
      value: mikrotik
    - meta: log_type
      value: mikrotik_failed_auth
    - meta: user
      expression: "evt.Parsed.invalid_user"
    - meta: source_ip
      expression: "evt.Parsed.source_ip"
    - target: evt.StrTime
      expression: evt.Parsed.timestamp
```

To this:

```
onsuccess: next_stage
#debug: true
filter: "evt.Parsed.program == 'mikrotik' and evt.Parsed.message contains 'input:' or evt.Parsed.message contains 'login'"
name: a1ad/mikrotik-logs
description: "Parse Mikrotik logs"
pattern_syntax:
  FIREWALL_DROP: "%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME} .* %{DATA:tag} input: in:%{DATA:if_in} out:%{DATA:if_out}, .* src-mac %{MAC:src_mac}, proto %{WORD:proto}.*, %{IP:src_ip}:%{INT:src_port}->%{IP:dst_ip}:%{INT:dst_port}, len %{INT:length}"
  AUTH_FAILED: "%{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME} .* login failure for user %{USERNAME:invalid_user} from %{IP:source_ip}"
nodes:
 - grok:
     name: "FIREWALL_DROP"
     apply_on: message
     statics:
       - meta: service
         value: tcp_udp
       - meta: log_type
         value: mikrotik_drop
 - grok:
     name: "AUTH_FAILED"
     apply_on: message
     statics:
       - meta: service
         value: mikrotik
       - meta: log_type
         value: mikrotik_failed_auth
       - meta: user
         expression: "evt.Parsed.invalid_user"

statics:
 - meta: source_ip
   expression: "evt.Parsed.source_ip"
 - target: evt.StrTime
   expression: evt.Parsed.timestamp
```

Parser and bruteforce checks are passing, but there is a problem with the mikrotik-scan-multi_ports scenario:

```
cscli hubtest run mikrotik-scan-multi_ports
INFO[19-03-2023 23:19:44] Running test 'mikrotik-scan-multi_ports'     
WARN[19-03-2023 23:19:52] Assert file '/home/jeroen/hub/.tests/mikrotik-scan-multi_ports/scenario.assert' is empty, generating assertion: 

len(results) == 0


Please fill your assert file(s) for test 'mikrotik-scan-multi_ports', exiting
```

The strange thing is that the explain is looking good?!
```

cscli hubtest explain mikrotik-scan-multi_ports
line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:25, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:28, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:30, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:38, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:39, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:37, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:24, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:26, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:27, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:31, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:32, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:34, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:36, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:29, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:33, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:35, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports

line: 2023-03-18T20:36:59.594792+01:00 10.120.127.1 firewall,info drop-tcp input: in:ether1-WAN out:(unknown 0), connection-state:new src-mac 00:17:10:88:bc:02, proto TCP (SYN), 36.97.161.219:59388->80.82.202.145:23, len 40
	├ s00-raw
	|	├ 🟢 crowdsecurity/non-syslog (first_parser)
	|	└ 🔴 crowdsecurity/syslog-logs
	├ s01-parse
	|	└ 🟢 a1ad/mikrotik-logs (+13 ~2)
	├ s02-enrich
	|	└ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
	├-------- parser success 🟢
	├ Scenarios
		└ 🟢 a1ad/mikrotik-scan-multi_ports
```

But yeah, no assertions from the hubtest. What did i do wrong?

**Comment by LaurenceJJones** [comment]
> 

Looks like in your parser your not setting the `onsuccess: next_stage` anywhere so the hubtest isnt getting to the scenario stage.

**Comment by LePresidente** [comment]
Tests looks fine, when i checked out locally, also looks like the PR tests were fine as well?

<code>
/mnt/f/Github Projects/hub-a1ad$ sudo cscli  hubtest run mikrotik-scan-multi_ports
INFO[20-03-2023 15:22:25] Running test 'mikrotik-scan-multi_ports'
INFO[20-03-2023 15:22:29] Test 'mikrotik-scan-multi_ports' passed successfully (105 assertions)
────────────────────────────────────
 Test                        Result
────────────────────────────────────
 mikrotik-scan-multi_ports   ✅
────────────────────────────────────
/mnt/f/Github Projects/hub-a1ad$ sudo cscli  hubtest run mikrotik-scan-multi_ports
INFO[20-03-2023 15:25:35] Running test 'mikrotik-scan-multi_ports'
INFO[20-03-2023 15:25:39] Test 'mikrotik-scan-multi_ports' passed successfully (105 assertions)
────────────────────────────────────
 Test                        Result
────────────────────────────────────
 mikrotik-scan-multi_ports   ✅
────────────────────────────────────
/mnt/f/Github Projects/hub-a1ad$ sudo cscli  hubtest run mikrotik-logs
INFO[20-03-2023 15:26:53] Running test 'mikrotik-logs'
INFO[20-03-2023 15:26:57] Test 'mikrotik-logs' passed successfully (223 assertions)
────────────────────────
 Test            Result
────────────────────────
 mikrotik-logs   ✅
────────────────────────
/mnt/f/Github Projects/hub-a1ad$ sudo cscli  hubtest run mikrotik-bf
INFO[20-03-2023 15:26:59] Running test 'mikrotik-bf'
INFO[20-03-2023 15:27:04] Test 'mikrotik-bf' passed successfully (51 assertions)
──────────────────────
 Test          Result
──────────────────────
 mikrotik-bf   ✅
──────────────────────
</code>

**Comment by a1ad** [comment]
> > 
> 
> EDIT: ignore me just seen you put it at the very top, which if you have nested grok patterns best to put it at the grok level rather than root.

check: https://hub.crowdsec.net/author/crowdsecurity/configurations/sshd-logs, the onsucces is at the top also.

**Review by LaurenceJJones — APPROVED** [review]
LGTM

**Pull request merged**
