### PR TITLE
Add vaultwarden parser, scenario and collection

### PR DESCRIPTION
**Pull request by Dominic-Wagner**
Add vaultwarden parser, scenario and collection

### CODE REVIEW

**Comment by andreasbrett** [comment]
I checked for some more log messages that might be interesting to detect. Some of them I tested on my vaultwarden instance, while I derived the rest from vaultwarden's code (e.g. https://github.com/dani-garcia/vaultwarden/blob/08f0de7b46d36a4e974d8e7b25a9786168cd38a5/src/api/core/two_factor/duo.rs#L297)


**2fa - Authenticator app / TOTP** (tested)
`[2022-02-04 20:37:42.887][vaultwarden::api::core::two_factor::authenticator][ERROR] Invalid TOTP code! Server time: 2022-02-04 19:37:42 UTC IP: 192.168.123.123`

**2fa - Google Duo**
`[2022-02-04 20:37:42.887][vaultwarden::api::core::two_factor::duo][ERROR] Error validating duo authentication`

**2fa - Email Token**
`[2022-02-04 20:37:42.887][vaultwarden::api::core::two_factor::email][ERROR] Token is invalid`

**2fa - U2F**
`[2022-02-04 20:37:42.887][vaultwarden::api::core::two_factor::u2f][ERROR] error verifying response`

**2fa - WebAuthn**
`[2022-02-04 20:37:42.887][vaultwarden::api::core::two_factor::webauthn][ERROR] Credential not present`

**2fa - Yubikey** (tested)
`[2022-02-04 20:37:42.887][vaultwarden::api::core::two_factor::yubikey][ERROR] Failed to verify Yubikey against OTP server`

**Emergency Access** (tested)
`[2022-02-04 20:44:05.447][vaultwarden::api::core::emergency_access][ERROR] Emergency access not valid.`

**Admin Login** (tested)
`[2022-02-04 20:39:53.343][vaultwarden::api::admin][ERROR] Invalid admin token. IP: 192.168.123.123`

**Comment by Dominic-Wagner** [comment]
@andreasbrett I added both the totp and admin login failures as they log an IP. As for the incomplete 2FA login, vaultwarden automaticaly sends an E-Mail notification to the user.

**Comment by blotus** [comment]
Hello,

Thanks for the PR, It looks good to me.

I'd request just one change: you've put everything in the `crowdsecurity` folder, but set the author to `Dominic Wagner`.
Can you change the author to `Dominic-Wagner` and put the collections/parsers/scenarios in a folder named `Dominic-Wagner` (or anything you want, just avoid spaces, and the names must to be consistent or the hub will generate a wrong `cscli` command for installation) ?

**Comment by Dominic-Wagner** [comment]
Hello @blotus,

thank you for your feedback, I changed the author and folder accordingly.

**Pull request merged**
