### PR TITLE
add http_verb in Meta in haproxy-logs

### PR DESCRIPTION
**Pull request by djuhnix**
Add missing field `http_verb` in `Meta` for haproxy-logs not synced with nextcloud-whitelist

---
Linked to  #1019

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Hey I just add the update test and also I saw haproxy was missing a s02 test so we can ensure the properties are correctly parsed

**Comment by LaurenceJJones** [comment]
Dont suppose you have any lines that should be whitelisted by the nextcloud whitelist you can redact the IP address and we can create a test case to ensure it doesnt break in future updates

**Comment by djuhnix** [comment]
Thank you for adding test for it, I was struggling on how to generate them correctly. 

This line could help you 
```
Apr  4 14:30:19 hap-1 haproxy[3946303]: 11.22.33.44:55032 [04/Apr/2024:14:30:18.885] front_https~ back_nextcloud/web.domain.sh 0/0/0/169/169 404 1541 - - ---- 5715/616/96/15/0 0/0 "PROPFIND /remote.php/webdav/User/Name/Backup/Free%20Studio/domain.com/05-07-2023/Wordpress/analytics-matomo/plugins/Events/lang/hu.json HTTP/1.1"
```

**Comment by LaurenceJJones** [comment]
> Thank you for adding test for it, I was struggling on how to generate them correctly.
> 
> This line could help you
> 
> ```
> Apr  4 14:30:19 hap-1 haproxy[3946303]: 11.22.33.44:55032 [04/Apr/2024:14:30:18.885] front_https~ back_nextcloud/web.domain.sh 0/0/0/169/169 404 1541 - - ---- 5715/616/96/15/0 0/0 "PROPFIND /remote.php/webdav/User/Name/Backup/Free%20Studio/domain.com/05-07-2023/Wordpress/analytics-matomo/plugins/Events/lang/hu.json HTTP/1.1"
> ```
> 
> edit: should I add it to the `.tests/haproxy-logs/` directory ?

Dont worry I will add a new test section for the nextcloud whitelist for haproxy directly. You can leave the rest to me, I will ping you to have a second pair of 👀 to make sure I havent messed up but great work! 👍🏻

**Comment by LaurenceJJones** [comment]
Awesome with your blessing @djuhnix that should be updated tests for haproxy and include a test case to ensure nextcloud does whitelist that case you want! ✨

**Comment by djuhnix** [comment]
Thank you for supporting @LaurenceJJones  ! 

I would like to go further with nextcloud whitelist, I don't know if it is exhaustive but it seems that some patterns are not fully handle by the parser. How can I evaluate those patterns as needed to be whitelisted or true positive ?

And Is there a way with `cscli` or crowdsec.log to list requests whitelisted by the parser to check if it is working ? (I think that only postoverflows whitelists are logs ?)

**Comment by LaurenceJJones** [comment]
> Thank you for supporting @LaurenceJJones !
> 
> I would like to go further with nextcloud whitelist, I don't know if it is exhaustive but it seems that some patterns are not fully handle by the parser. How can I evaluate those patterns as needed to be whitelisted or true positive ?
> 
> And Is there a way with `cscli` or crowdsec.log to list requests whitelisted by the parser to check if it is working ? (I think that only postoverflows whitelists are logs ?)

NGL its pretty difficult unless you know which lines should be parsed. If there is a line that should be handle when running 

```
cscli explain
```

It will return true or false for that node then either we need to check the whitelist or haproxy again to see if a value is not set properly

**Comment by djuhnix** [comment]
Yes I guess, I will continue to inspect it and create a issue if I found anything else. Thank you for your help !

**Pull request merged**
