### PR TITLE
Add parser and scenario for Lemonldap::NG

### PR DESCRIPTION
**Pull request by dani**
Here's a parser and scenario to detect brutforce on Lemonldap::NG (only tested with an LDAP auth backend as it's what I run, but can be extended later to support more use cases).

### CODE REVIEW

**Comment by he2ss** [comment]
Hi @dani,

Thanks for this MR :+1: 
Just same comment as https://github.com/crowdsecurity/hub/pull/171, if it's possible to have a collection containing both parser and scenario, and also update the github orga.

After merging this MR, will add tests on it. Could you please provide us some logs. I already have those :
```
# Failed Authentication
[Thu Mar  4 10:22:01 2021] [LLNG:52] [warn] foo.bar was not found in LDAP directory (5.6.7.8)
[Thu Mar  4 10:22:01 2021] [LLNG:52] [warn] Bad password for dwho (5.6.7.8)

# Failed authentication with Combination module
[Thu Mar  4 10:22:04 2021] [LLNG:52] [warn] All schemes failed for user dwho (2.2.2.2)
```
If I miss some other important logs please let me know.

**Comment by dani** [comment]
OK, will update this ASAP

**Comment by dani** [comment]
Here are some log samples
```
Mar  1 04:07:11 proxyin LLNG[73088]: [warn] CamillaNazario7 was not found in LDAP directory (10.18.21.22)
Mar  2 22:57:38 proxyin LLNG[106537]: [warn] Bad password for dani (10.18.21.22)
Mar  2 22:55:23 sas lemonldap-ng[30304]: Lemonldap::NG : BadUser was not found in LDAP directory (10.18.21.22)
Mar  2 22:57:10 sas lemonldap-ng[22384]: Lemonldap::NG : Bad password for admin (10.18.21.22)
``

**Comment by he2ss** [comment]
Thanks for your contribution ! 
I'll merge this to a specific branch, add tests then merge it to master.

**Pull request merged**
