### PR TITLE
Add Zimbra parser and scenario

### PR DESCRIPTION
**Pull request by dani**
Here's a parser and scenario for Zimbra. Seems quite effective (129 overflows over night on a single installation).
Note : I used %{NGUSER} here beacuse %{USERNAME} doesn't match email-style usernames, while %{NGUSER} does

### CODE REVIEW

**Comment by buixor** [comment]
great MR again :cupid: Just to be sure before merging, are you part of the `fws` org on github ?

**Comment by dani** [comment]
fws is the short name of the company I work for : Firewall Services. Unfortunatly, the fws github org isn't from us, I don't know who controls it.

**Comment by buixor** [comment]
@dani then if you don't mind using `dani` as the org in collection names ? I wouldn't want a 3rd party to claim it later, or to receive change requests :sweat_smile: 

as this appears in the hub directly, ie. https://hub.crowdsec.net/author/ltsich/configurations/http-w00tw00t

**Comment by dani** [comment]
For the collection, indeed. Would you like me to update the PR ? As for the collection name, I'd prefer my company taking credits. If fws can't be used, maybe firewallservices/zimbra (it's a bit long but ...). I've just created the firewallservices github org :-)

**Comment by buixor** [comment]
> For the collection, indeed. Would you like me to update the PR ?
Either you upgrade the PR or I'll do it after the merge, just wanted to be sure you're ok with that.

> I've just created the firewallservices github org :-)
Perfect, do you mind updating the PR for this ?

Thanks !

**Comment by buixor** [comment]
great :+1:

**Review by buixor — APPROVED** [review]

**Comment by buixor** [comment]
@dani it's all good for me and I'm going to merge this. Would you mind providing a sample log of such an attack so I can add tests ? (even privately if you want and I'll take care of anomymizing them)

**Review by buixor — APPROVED** [review]

**Comment by dani** [comment]
Here're some sample : 
```
2021-03-03 19:26:38,616 INFO  [qtp93314457-137:https://zmtest-web.fws.fr:7071/service/admin/soap/AuthRequest] [name=dani@zmtest.fws.fr;oip=192.168.7.101;port=52016;ua=ZimbraWebClient - GC88 (Linux);soapId=9fd8101;] SoapEngine - handler exception: authentication failed for [dani@zmtest.fws.fr], invalid password
2021-03-03 19:51:53,762 INFO  [qtp93314457-324:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [oip=192.168.7.15;oport=57752;oproto=smtp;soapId=688cb579;] SoapEngine - handler exception: authentication failed for [sebastien.bouttier], account not found
2021-03-03 19:53:06,536 WARN  [qtp93314457-589:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [name=contact@zmtest.fws.fr;oip=192.168.7.15;oport=41496;oproto=smtp;soapId=688cb582;] SoapEngine - handler exception
2021-03-03 19:53:09,514 WARN  [qtp93314457-324:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [name=contact@zmtest.fws.fr;oip=192.168.7.15;oport=53544;oproto=smtp;soapId=688cb583;] SoapEngine - handler exception
2021-03-03 19:53:15,744 INFO  [qtp93314457-589:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [oip=192.168.7.15;oport=24304;oproto=smtp;soapId=688cb584;] SoapEngine - handler exception: authentication failed for [coe@zmtest.fws.fr], account not found
2021-03-03 19:55:02,986 INFO  [qtp93314457-324:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [oip=192.168.7.15;oport=32628;oproto=smtp;soapId=688cb591;] SoapEngine - handler exception: authentication failed for [coffee@zmtest.fws.fr], account not found
2021-03-03 19:56:37,540 INFO  [qtp93314457-589:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [oip=192.168.7.15;oport=59448;oproto=smtp;soapId=688cb5a2;] SoapEngine - handler exception: authentication failed for [sebastien.bouttier@zmtest.fws.fr], account not found
2021-03-03 19:56:53,175 INFO  [qtp93314457-589:smtp://store.zmtest.fws.fr:7073/service/admin/soap/] [oip=192.168.7.15;oport=40970;oproto=smtp;soapId=688cb5a4;] SoapEngine - handler exception: authentication failed for [cog@zmtest.fws.fr], account not found
2021-03-03 20:20:07,193 INFO  [ImapSSLServer-1] [ip=10.29.1.17;oip=192.168.7.101;via=10.29.1.17(nginx/1.7.1);ua=Zimbra/8.8.15_GA_3996;cid=57;] imap - authentication failed for [dani@zmtest.fws.fr] (invalid password)
```

**Comment by buixor** [comment]
I'm going to suggest you a MR (on yours) to be sure that the timestamps are correctly extracted : it will allow those logs as well to be processed in "forensic mode" https://doc.crowdsec.net/Crowdsec/v1/user_guide/forensic_mode/

But that's on my side, no worries

**Comment by buixor** [comment]
I made a pr to your repo : https://github.com/dani/hub/pull/1 
I plan as well to add tests before merging

**Comment by buixor** [comment]
Thanks @dani, I'm merging this to non-master branch because I have some stuff to fix in the CI and I don't want to bother you.
Much appreciated !

**Pull request merged**
