### PR TITLE
Kerio Connect security.log

### PR DESCRIPTION
**Pull request by ToeiRei**
Requested parser and scenario in #437 and finally had the time to do it myself.

### CODE REVIEW

**Comment by ToeiRei** [comment]
The timings may need some tuning due to kerio antispam measures already in place.

**Comment by he2ss** [comment]
Hi @ToeiRei,

Did you had some time to finish the tuning ?
Also, this parser and scenario needs some tests. You can use [cscli hubtest](https://docs.crowdsec.net/docs/next/cscli/cscli_hubtest/) to generate new tests suite.

**Comment by ToeiRei** [comment]
Sorry for the late reply. I'll do the hubtest as soon as I'm back home

**Comment by ToeiRei** [comment]
I found a few issues with the blocks from kerio which I find disturbing.... their log entries are based on their detection

**Comment by LaurenceJJones** [comment]
Converting to draft to proceed please upload some tests

**Comment by TimmiORG** [comment]
Hi @ToeiRei 
are you still working on this?
If yes, can I help? I'm quite interested to get this working as well.

**Comment by ToeiRei** [comment]
I had the project on hold as the blocklist mirror wasn't too helpful. Hit me up on discord and we'll get the show on the road again

**Pull request closed without merging**
