### PR TITLE
Update caddy-logs.yaml to include http_version

### PR DESCRIPTION
**Pull request by plttn**
Adds HTTP version parsing to Caddy parser, resolving an unintended conflict with the `http-dos-invalid-http-versions` scenario.

I think I still need to add some tests for this, but wanted to get a PR going.

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

I just merged #943 which should stop false triggers, however, I still welcome your PR as we need parser to set the version.

I dont feel the need to have a specific test for the scenario, however, just re running the parsers will add the version to the test.

**Comment by plttn** [comment]
Sorry for not getting back to to you right away. Just to confirm, are there any other changes I need to make with this PR?

**Comment by LaurenceJJones** [comment]
> Sorry for not getting back to to you right away. Just to confirm, are there any other changes I need to make with this PR?

You need to regenerate the parser tests. I can do it for you in a little while.

**Comment by plttn** [comment]
Thanks @LaurenceJJones!

**Pull request merged**
