### PR TITLE
Add parser and scenario aidalinfo/tcpudp-flood-traefik

### PR DESCRIPTION
**Pull request by Killian-Aidalinfo**
Hello Crowdsec team !
Here is my parser and scenario linked to the article for tcp/udp flood protection with traefik reverse proxy. I followed the workflow well it seems. I've done the hub test and the hub explain.

I remain at your disposal if needed!

Thanks.

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Also I would suggest using [cache_size](https://docs.crowdsec.net/docs/next/scenarios/format#cache_size) to limit how many items are held in memory because 1000 would most likely cause RAM issues

**Comment by Killian-Aidalinfo** [comment]
Hi !
@LaurenceJJones Thank you for your recommandation I've added cache size of 300 for optimize memory. This is ok you think ?
@buixor I've added assert file ! I think that ok :)

cli result :
☁  hub [tcpudp-flood-traefik-aidalinfo] ⚡  ../cscli -c ../dev.yaml hubtest run tcpudp-flood-traefik
INFO[16-01-2024 13:43:28] Running test 'tcpudp-flood-traefik'          
INFO[16-01-2024 13:43:32] Test 'tcpudp-flood-traefik' passed successfully (94 assertions) 
───────────────────────────────
 Test                   Result 
───────────────────────────────
 tcpudp-flood-traefik   ✅     
───────────────────────────────

**Comment by LaurenceJJones** [comment]
I still think 300 too large, other than once it overflows what will the user do with the information? other than they already know it to be a tcp/udp attack

**Comment by Killian-Aidalinfo** [comment]
Ok I understand, Thank you !

**Review by buixor — APPROVED** [review]
lgtm

**Pull request merged**
