### PR TITLE
add nextcloud parser, bruteforce detection and collection

### PR DESCRIPTION
**Pull request by umglurf**

### CODE REVIEW

**Comment by umglurf** [comment]
I'm not sure why the tests fail, they run ok locally. Seems to be something with the order that changes?

**Comment by umglurf** [comment]
> I'm not sure why the tests fail, they run ok locally. Seems to be something with the order that changes?

Found an error in the scenario, pushed fix

**Comment by buixor** [comment]
thanks for the PR, we'll quickly have a look !

**Comment by buixor** [comment]
Hello, Sorry for lagging on this PR @umglurf 

It seems that the latest tests are not passing, can you have a look ? Besides that, looks good to me.

**Comment by umglurf** [comment]
> Hello, Sorry for lagging on this PR @umglurf
> 
> It seems that the latest tests are not passing, can you have a look ? Besides that, looks good to me.

Hi, I just pushed a fix for some typos, it ran ok locally for me now

**Comment by umglurf** [comment]
> > Hello, Sorry for lagging on this PR @umglurf
> > It seems that the latest tests are not passing, can you have a look ? Besides that, looks good to me.
> 
> Hi, I just pushed a fix for some typos, it ran ok locally for me now

Not sure why it fails now, when i run hubtest locally on the branch it does not fail. Do you have any idea what is wrong?

**Comment by buixor** [comment]
No, I came to the same conclusion as you : I run CI on your branch and it works, we're investigating it and I'll keep you posted asap :)

**Comment by buixor** [comment]
@umglurf : I'm merging into non-master to test properly

**Pull request merged**
