### PR TITLE
[REQUIRE CROWDSEC CHANGE] Add support for Caddy 2.5 log format

### PR DESCRIPTION
**Pull request by LePresidente**
Fixes https://github.com/crowdsecurity/hub/issues/408

### CODE REVIEW

**Comment by LePresidente** [comment]
I think the time format is not supported by dateparse-enrich so its just getting the current time of the system in stead of the logs

**Comment by adworacz** [comment]
Any word on getting Crowsdec updated so this can be merged? I'm held off on updating my Caddy server to give enough time for Crowdsec to get released, but Caddy is already on 2.5.1 and over a month since the 2.5.0 release.

**Comment by Lednerb** [comment]
With the latest release and https://github.com/crowdsecurity/crowdsec/pull/1576 it should be possible to implement an optimized approach for parsing the newer caddy logs.

**Comment by sbs2001** [comment]
@LePresidente could you please rebase your PR with latest master branch ?

**Comment by rgevaert** [comment]
Note: I would love to see this fixed. I was looking at adding either corazo WAF to Caddy or Crowsec. I choose for Crowdsec because there is a working Caddy module for download. Being bitten by this made me reconsider my decision. But I am happy to wait a couple of days for this to be solved ;). Thanks in advance.

**Comment by LePresidente** [comment]
still failing due to 
```
results["s02-enrich"]["crowdsecurity/dateparse-enrich"][1].Evt.Enriched["MarshaledTime"]
```
being the current time instead of the log time.

**Comment by sbs2001** [comment]
@LePresidente  I've opened PR in your fork for fix.  Basically the date is not being transformed into a format crowdsec can recognize

**Comment by LePresidente** [comment]
Ah thanks for that didn't know you could just reorder the expression to match something already supported. I'll take note of that

**Review by AlteredCoder — APPROVED** [review]

**Pull request merged**
