### PR TITLE
Update web_php log parser

### PR DESCRIPTION
**Pull request by baudneo**
ZoneMinder has added user configurable PHP date formats. This covers legacy and US/CAN format, users with custom formats will need to modify the GROK pattern.

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
As always thank you @baudneo ! I will review it today.

**Comment by LaurenceJJones** [comment]
Do think there be value adding
```
collections:
  - baudneo/zoneminder_http-cve.yaml
```
To the original zoneminder collections so if anyone has it installed originally they can automatically get the new cve collection without having to find it manually?

**Comment by baudneo** [comment]
Yes that sounds like a good idea!

**Review by LaurenceJJones — APPROVED** [review]
LGTM

**Pull request merged**
