### PR TITLE
Update nginx-logs.yaml to accept host:port combined NCSA patter

### PR DESCRIPTION
**Pull request by click**
Expand grok-match for NCSA vcombined format

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

Just to ask because I never seen this before, you are using the `server_name` directive in nginx to have `domain`  + `port` so when you have the log format set to:

```
    log_format main '$server_name $remote_addr - $remote_user [$time_local] '
                '"$request" $status $body_bytes_sent '
                '"$http_referer" "$http_user_agent"';
    # Logging
    access_log             /var/log/nginx/access.log main;
```

The `$server_name` is what you changed here?

**Comment by LaurenceJJones** [comment]
Okay I just tested it with ip's but would be the same for domains:

```
192.168.121.181:8080 192.168.121.1 - - [14/Nov/2024:09:02:03 +0000] "GET / HTTP/1.1" 200 11 "-" "curl/8.11.0"
192.168.121.181 192.168.121.1 - - [14/Nov/2024:09:02:05 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/8.11.0"
```

```
 cat sites-available/* | grep server_name
        server_name 192.168.121.181;
        server_name 192.168.121.181:8080;
```

**Review by blotus — APPROVED** [review]

**Review by LaurenceJJones — APPROVED** [review]

**Comment by LaurenceJJones** [comment]
We are investigating an issue on our side, you changes are published, however, there currently issue downloading them remotely.

I will update this PR once we have it resolved.

**Comment by LaurenceJJones** [comment]
Update: this should now be live and can be downloaded via updates

```
cscli hub update && cscli hub upgrade
```

**Pull request merged**
