### PR TITLE
Add parser and scenario for pf logs (PfSense)

### PR DESCRIPTION
**Pull request by dani**
I've only tested it with PfSense, but it can probably work with other FreeBSD. It requires new patterns, added in https://github.com/crowdsecurity/crowdsec/pull/662

### CODE REVIEW

**Comment by buixor** [comment]
Hello @dani !

I see that you opened a PR in crowdsec to add the patterns (https://github.com/crowdsecurity/crowdsec/pull/662).
However, having the grok patterns in the code is something that we try to get away from [1].
Would you mind using the [pattern_syntax](https://doc.crowdsec.net/Crowdsec/v1/references/parsers/#pattern_syntax) directive instead so that patterns can be defined directly in the config ?

It should be something like :

```yaml
filter: "evt.Parsed.program == 'filterlog' or evt.Parsed.message matches '^filterlog:'"
name: firewallservices/pf-logs
description: "Parse packet filter logs"
pattern_syntax:
  PF_UDP_DATA: '%{INT:src_port},%{INT:dest_port},%{INT:data_length}'
  PF_TCP_DATA: '%{PF_UDP_DATA},%{WORD:tcp_flags},%{INT:sequence_number},%{INT:ack_number},%{INT:tcp_window},%{DATA:urg_data},%{DATA:tcp_options}'
  PF_PROTOCOL_DATA: '(%{PF_TCP_DATA}|%{PF_UDP_DATA})'
  PF_IP_DATA: '%{INT:length},%{IP:src_ip},%{IP:dest_ip},'
  PF_IPv4_DATA: '%{BASE16NUM:ip4_tos},,%{INT:ip4_ttl},%{INT:ip4_id},%{INT:ip4_offset},%{WORD:ip4_flags},%{INT:ip4_proto_id},%{WORD:ip4_proto},'
  PF_IPv6_DATA: '%{BASE16NUM:ip6_class},%{DATA:ip6_flow_label},%{INT:ip6_hop_limit},%{WORD:ip6_proto},%{INT:ip6_proto_id},'
  PF_IP_SPECIFIC_DATA: '(%{PF_IPv4_DATA}|%{PF_IPv6_DATA})'
  PF_LOG_DATA: '%{INT:rule},(%{INT:sub_rule})?,,%{INT:tracker},%{DATA:iface},%{WORD:reason},%{WORD:action},%{WORD:direction},%{INT:ip_ver},'
  PF_FILTERLOG: '%{PF_LOG_DATA}%{PF_IP_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}'
grok:
  pattern: "%{PF_FILTERLOG}"
  apply_on: message
---
#debug: true
filter: "evt.Parsed.action == 'block'"
name: firewallservices/pf-logs-drop
onsuccess: next_stage
statics:
    - meta: service
      value: tcp
    - meta: log_type
      value: pf_drop
    - meta: source_ip
      expression: "evt.Parsed.src_ip"
```

I have tried it loads (so syntax is correct), but I didn't had the chance to try it because I have no pf logs.


[1] mostly because it means we wouldn't be able to shit your collection before the other MR is merged and a new crowdsec version is released :disappointed:

**Comment by dani** [comment]
Yeah no prob. I though having patterns in /etc/crowdsec/patterns was the preferred way, but it makes sense to have it in the parsers themselves. I'll update the PR ASAP

**Comment by dani** [comment]
Mmmm, looks like we can't reference another pattern name defined at the same place. Eg
```
pattern_syntax:
  PF_UDP_DATA: '%{INT:src_port},%{INT:dest_port},%{INT:data_length}'
  PF_TCP_DATA: '%{PF_UDP_DATA},%{WORD:tcp_flags},%{INT:sequence_number},%{INT:ack_number},%{INT:tcp_window},%{DATA:urg_data},%{DATA:tcp_options}'
  PF_PROTOCOL_DATA: '(%{PF_TCP_DATA}|%{PF_UDP_DATA})'
```

gives
```
mars 09 16:07:10 crowdsec crowdsec[343911]: time="09-03-2021 16:07:10" level=fatal msg="Error decoding parsing configuration file '/etc/crowdsec/parsers/s01-parse/pf-logs.yaml': yaml: line 7: did not find expected key"
```

(line 7 being PF_PROTOCOL_DATA)

**Comment by dani** [comment]
OK, will update this PR ASAP (most likely not today, as I've been bitten quite hard by the OVH DC burning yesterday ;-) )

**Comment by buixor** [comment]
ah no worries and no stress, just wanted to keep you posted on this issue !

et bon courage pour la recuperation d'ovh, force a vous !

**Comment by dani** [comment]
Should be better now (althought I couldn't test it yet ^^)

**Comment by buixor** [comment]
oh that was completely overdue to be merged, by bad @dani !

**Comment by buixor** [comment]
merging in another branch do deal with conflicts

**Pull request merged**
