### PR TITLE
Added seperate Generic 401 Http Error Scenario, this is an alternative to PR #409

### PR DESCRIPTION
**Pull request by LePresidente**
Added Generic 401 Scenario this will stop bruteforcing from a reverse proxy to Gotify for example using the 401 Http error code.

### CODE REVIEW

**Comment by buixor** [comment]
Hey @LePresidente,

PR looks good to me, we're debating whether it should go in a more generic collection (ie. base-http-scenarios)

**Comment by LePresidente** [comment]
I was debating with myself about the same thing, I did it first in nginx-http-generic-bf 
<https://github.com/crowdsecurity/hub/pull/409>

Though not sure if it would cause false positives and it will  become enabled by default since its already part of a generic collection

**Comment by LePresidente** [comment]
Reopened the other PR as well since its possibly on the cards

**Comment by buixor** [comment]
let's favor the other one, closing this one, thanks !

**Pull request closed without merging**
