### PR TITLE
fix(paperless-ngx): Remove ^ from the patterns to allow container log…

### PR DESCRIPTION
**Pull request by dimatha**
First of all - Thanks for the great work ! 

It seems like we have to remove the start of the line matching filter to allow container logs to be parsed.

### CODE REVIEW

**Comment by dimatha** [comment]
@andreasbrett, could please have a look ? Thanks !

**Comment by andreasbrett** [comment]
> @andreasbrett, could you please have a look ? Thanks !

LGTM. I think we could also get rid of the trailing `$`.

**Review by andreasbrett — APPROVED** [review]
still works and I think we should also get rid of the trailing `$`. there's no need to have this regex utterly strict.

**Comment by dimatha** [comment]
@andreasbrett  done ! 

Thanks

**Review by LaurenceJJones — COMMENTED** [review]
LGTM

**Pull request merged**
