### PR TITLE
Authelia-logs json parser could catch successful login attempts as bad.

### PR DESCRIPTION
**Pull request by LePresidente**
There is a possibility the JSON parser will return successful login attempts as bad attempts and ban the offending IP. This makes sure we check the entire string.

### CODE REVIEW

**Comment by buixor** [comment]
Thanks, do you mind adding some test for the false positive so we can identify future regressions ?

**Review by buixor — CHANGES_REQUESTED** [review]
lgtm, tests would be nice

**Comment by LePresidente** [comment]
@buixor Ok I'm going to need some here here, The Grok Pattern looks to be correct but the Successful lines are still being detected by the Grok Pattern where it shouldn't be the case

**Comment by LePresidente** [comment]
This is only happening for the Json Parsed Lines, The CLF log lines are working correctly.

**Comment by LePresidente** [comment]
nevermind figured out the issue, I was not correctly understanding the json parser.

**Review by buixor — APPROVED** [review]
lgtm

**Pull request merged**
